name: simplelibrary
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^3.0.0
  equatable: ^1.0.0
  shared_preferences: ^0.5.6+3

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
